import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';
import { supabase } from '../supabase';
import useIsAuth from '../hooks/index';
import Card from '../components/Card';
import styled from 'styled-components';

const CardContainer = styled.div`
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
`;

const Home = () => {
  const [cursos, setCursos] = useState([]);

  const getCourses = async () => {
    let { data: cursos, error } = await supabase
      .from('cursos')
      .select('*')
      .eq('habilitado', true);

    setCursos(cursos);
  };

  useEffect(() => {
    getCourses();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>L-Platform</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>L-Platform</h1>
      <CardContainer>
        {cursos?.map((curso) => (
          <Card
            key={curso.id}
            name={curso.name}
            price={curso.price}
            imageURL={curso.imageUrl}
            discount={curso.discount}
          />
        ))}
      </CardContainer>
    </div>
  );
};

export default Home;
